version: '3'
services:
  db:
    image: mariadb:10.3
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_ROOT_HOST: '%'
    volumes:
      - db:/var/lib/mysql
    ports:
      - "53306:3306"

  redis:
    image: redis:5.0
    ports:
      - "56379:6379"

volumes:
  db:
