source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "2.6.6"

gem "rails", "~> 6.0.2", ">= 6.0.2.2"
gem "puma", "~> 4.1"
gem "bootsnap", ">= 1.4.2", require: false

gem "mysql2"
gem "ridgepole"
gem "redis-actionpack"

gem "warden"
gem "cancancan"

group :development do
  gem "annotate"

  gem "pry-byebug"
  gem "better_errors"
  gem "binding_of_caller"

  gem "web-console", ">= 3.3.0"
  gem "listen", ">= 3.0.5", "< 3.2"
  gem "spring"
  gem "spring-watcher-listen", "~> 2.0.0"
end
